FROM node:24-alpine AS build

WORKDIR /app

# Copy and install dependencies
COPY package*.json .
COPY ./backend/package*.json ./backend/
COPY tsconfig*.json .
COPY ./backend/tsconfig*.json ./backend/
RUN npm i

COPY ./backend/ ./backend/

RUN npm run build:backend

EXPOSE 5000

CMD ["npm", "run", "dev:backend"]
