# Build stage
FROM node:24-alpine AS build

# Set working directory
WORKDIR /app

ARG VITE_API_URL="http://localhost:5000/api"

# Copy and install dependencies
COPY package*.json .
COPY ./frontend/package*.json ./frontend/
COPY tsconfig*.json .
COPY ./frontend/tsconfig*.json ./frontend/
RUN npm i

# Copy source code
COPY ./frontend/ ./frontend/

# Build app
RUN npm run build:frontend

# Production stage
FROM nginx:alpine

# Copy files for built app
COPY --from=build /app/frontend/dist /usr/share/nginx/html

# Serve app in exposed port 80
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
